### ISSUE TITLE
Pulling questions and listening for answers

### ISSUE THREAD

**Issue by Playmatics2** [Learnosity/learnosity-sdk-nodejs#12]
Hello,
Forgive me, but since this seems to be the only place with any nodejs learnosity code, and the only documentation that exists is how to initialize it, can you please explain and/or add code samples to show:
1) how to tell the learnosity window div which type of question to show the user (multiple choice, fill in the blank,etc.)
2) how to listen for the answer to that question (for example, ```document.getElementById("learnosity_assess").addEventListener("somelistener", function(){}); ``` 
Thanks.  I had trouble finding anything about how to do this in the linked documents, especially with them all being written in PHP.

**Comment by TheRealEdDawson** [comment]
Hello Playmatics! We've given these details to your assigned business development engineer who will follow up and show you the best way to render items and tie into Learnosity's events. Our team is always ready to help, over in our support system.
