### ISSUE TITLE
Publishing to NPM 

### ISSUE THREAD

**Issue by spmartin823** [Learnosity/learnosity-sdk-nodejs#5]
Hi, I was wondering if there is a reason why this package is not published to NPM. Would it be possible to publish to NPM in the near future?

**Comment by flakeparadigm** [comment]
Hi @spmartin823,

Getting the SDK into the NPM registry is indeed a goal of ours. I've added your report to our existing backlog entry which will help us better assess the priority of getting this done. If you want us to provide you with future updates when we are able to work it into a sprint, feel free to leave this issue open and we'll update you here.

Cheers,
Tyler
